project:
  type: website
  output-dir: docs

website:
  title: "BSRL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - post.qmd
      - competition.qmd
      - goal.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



