project:
  type: website
  output-dir: docs

website:
  title: "BSRL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - post.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



